// run this using `mongo cinemaville populate-movies.js`
db.movies.insertMany([
    {
        name: 'Rocky III',
        genre: 'action',
        year: 1982,
        actors: ['Sylvester Stalone', 'Mr. T'],
        image: 'https://images-na.ssl-images-amazon.com/images/I/51WJBnip6-L.jpg',
        video: 'https://www.youtube.com/embed/q4FhoXt8lFk',
    },
    {
        name: 'Lion King',
        genre: 'animation',
        year: 1994,
        actors: ['James Earl Jones', 'Kid from Home Improvement'],
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMwfebO0wboJcIYaFOyIPgMy9RPKWonCie-L4A2uzlS353azqC',
        video: 'https://www.youtube.com/embed/f0fReuRs890',
    },
    {
        name: 'Dumb & Dumber',
        genre: 'comedy',
        year: 1994,
        actors: ['Jim Carey', 'Jeff Daniels'],
        image: 'https://m.media-amazon.com/images/M/MV5BZDQwMjNiMTQtY2UwYy00NjhiLTk0ZWEtZWM5ZWMzNGFjNTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        video: 'https://www.youtube.com/embed/l13yPhimE3o',
    },
    {
        name: 'Toy Story',
        genre: 'animation',
        year: 1995,
        actors: ['Tom Hanks', 'Tim Allen'],
        image: 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SY1000_SX670_AL_.jpg',
        video: 'https://www.youtube.com/embed/KYz2wyBy3kc',
    },
    {
        name: 'The Ring',
        genre: 'horror',
        year: 2002,
        actors: ['Naomi Watts', 'Martin Henderson'],
        image: 'https://m.media-amazon.com/images/M/MV5BNDA2NTg2NjE4Ml5BMl5BanBnXkFtZTYwMjYxMDg5._V1_.jpg',
        video: 'https://www.youtube.com/embed/yzR2GY-ew8I',
    },
    {
        name: 'The Shawshank Redemption',
        genre: 'drama',
        year: 1994,
        actors: ['Tim Robbins', 'Morgan Freeman'],
        image: 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        video: 'https://www.youtube.com/embed/6hB3S9bIaco',
    },
])